from .register import Register
class system:
    chip_id = Register(name="chip_id",addr=0x0,size=0x4,mask=0xffffffff,default=0x2731803)
    chip_id_sw_en = Register(name="chip_id_sw_en",addr=0x4,size=0x1,mask=0x1,default=0x0)
    fast_clk_ctrl = Register(name="fast_clk_ctrl",addr=0x5,size=0x1,mask=0x33,default=0x0)
    gpio_tx_rx_sw_ctrl = Register(name="gpio_tx_rx_sw_ctrl",addr=0x6,size=0x1,mask=0x13,default=0x0)
    gpio_agc_rst_ctrl = Register(name="gpio_agc_rst_ctrl",addr=0x7,size=0x1,mask=0x13,default=0x0)
    gpio_agc_start_ctrl = Register(name="gpio_agc_start_ctrl",addr=0x8,size=0x1,mask=0x13,default=0x0)
    gpio_agc_gain_in_ctrl = Register(name="gpio_agc_gain_in_ctrl",addr=0x9,size=0x1,mask=0xff,default=0x0)
    gpio_agc_gain_out_ctrl = Register(name="gpio_agc_gain_out_ctrl",addr=0xa,size=0x1,mask=0xff,default=0x0)
    bist_amux_ctrl = Register(name="bist_amux_ctrl",addr=0xb,size=0x1,mask=0xcf,default=0x0)
    bist_ot_ctrl = Register(name="bist_ot_ctrl",addr=0xd,size=0x1,mask=0x33,default=0x0)
    bist_ot_temp = Register(name="bist_ot_temp",addr=0xe,size=0x1,mask=0xdf,default=0x80)
    bist_ot_rx_off_mask = Register(name="bist_ot_rx_off_mask",addr=0xf,size=0x3,mask=0x1fffff,default=0x0)
    bist_ot_tx_off_mask = Register(name="bist_ot_tx_off_mask",addr=0x12,size=0x3,mask=0x1fffff,default=0x0)
    spare = Register(name="spare",addr=0x1c,size=0x4,mask=0xffffffff,default=0xff0000ff)

    chip_id.doc = """Chip Identification / Chip Identifcation Shadow
(Big-endian, i.e MSB first).
This register doubles as Read-only (RO) Chip Idenfication and
Read/Write (RW) Chip Identification Shadow register.
Chip Identification Shadow is always written when this register
is written.
"""
    chip_id_sw_en.doc = """Configure access of Chip Idenification / Chip Identification Shadow register
chip_id_sw_en = 0:
	Read: Chip Identification, Write: Chip Identification Shadow
chip_id_sw_en = 1:
	Read/Write: Chip Identification Shadow"""
    fast_clk_ctrl.doc = """Fast clock control.
 Controls if the internal digital system clock
is generated by an external clock on GPIO DIG_CLK
or from an internal PLL synchronised to a reference
clock on REF_P/REF_N-pins.
The internal digital clock can also be fed out on GPIO DIG_CLK.
Bits
0	External source select
1	GPIO DIG_CLK output enable for fast clock
4	fast clock frequency select. (0 = 4xRef clock frequency, 1 = 5xRef clock frequency)
5	Ref clock select (1: 45 MHz, 0: 40 MHz)"""
    gpio_tx_rx_sw_ctrl.doc = """GPIO TX_RX_SW control
Bits
0	TX_RX_SW output value
1	TX_RX_SW output enable (1=enable, 0=disable)
4	TX_RX_SW input value (Read-only)"""
    gpio_agc_rst_ctrl.doc = """GPIO AGC_RST control
Bits
0	AGC_RST output value
1	AGC_RST output enable (1=enable, 0=disable)
4	AGC_RST input value (Read-only)"""
    gpio_agc_start_ctrl.doc = """GPIO AGC_START control
Bits
0	AGC_START output value
1	AGC_START output enable (1=enable, 0=disable)
4	AGC_START input value (Read-only)"""
    gpio_agc_gain_in_ctrl.doc = """GPIO AGC_GAIN_x input/output value (x=3, 2, 1 or 0)
Bits
3:0	AGC_GAIN_x output value (x corresponds to bit position)
7:4	AGC_GAIN_x input value (Read-only)"""
    gpio_agc_gain_out_ctrl.doc = """GPIO AGC_GAIN_x output control
Bits
3:0	AGC_GAIN_x output enable (1=enable, 0=disable, x corresponds to bit position)
7:4	AGC_GAIN_x source select (0=AGC state machine, 1=this register)"""
    bist_amux_ctrl.doc = """BIST Analog Mux Control
Controls which internal analog source is connected to the AMUX-pin and to the internal ADC.
Bits
3:0	Analog Mux select
6	DC Sense calibration (1=short DC sense diff input)
7	Analog mux enable
Analog mux select
0	BG PLL
1	BG TX
2	BG RX
3	Temperature
4	BB_RX
5	PLL/VCO
6	VCC PLL
7	TX Power Detector (Peak)
8	ADC reference
9	DC Sense I-channel
10	DC Sense Q-channel
11	DC Sense common mode
12	OTP control
13	TX Power detector (Envelope)
14	VCC PA * 3/4
15	VCC TX * 3/4"""
    bist_ot_ctrl.doc = """BIST Overtemp protection (OTP) control
Controls which OTP source to connect to AMUX-pin and ADC.
Enables/Disables OTP function and OTP Alarm function.
The OTP function controls which parts of the chip should be turned off, if the temperature becomes too high.
Normally it is sufficient that the temperature drops below the treshold, to resume the turned off parts on again.
The OTP Alarm function enables the OTP function to keep these parts off until the OTP Alarm bit has been cleared instead.
Bits
1:0	OTP control
4	OTP enable (0=disable)
5	OTP Alarm enable (0=disable)

OTP control
00	Temp Threshold
01	VDD 1.8 V 
10	VDD 1.2 V
11	VCC RX * 3/4"""
    bist_ot_temp.doc = """BIST OTP Temperature Threshold
Sets threshold level for comparator indicating whether temperature is ok or not.
OTP temperature OK bit shows this indication. OTP Alarm bit shows if any temperature not OK indication has occurred
since last time the OTP Alarm was cleared.
Bits
4:0	OTP threshold value
6	OTP Alarm (Read-only, Cleared when written with 1)
7	OTP temperature OK (Read-only)

Bits 7:6 interpretation
00	Currently temperature is too high, but not earlier.
01	Currently temperature is too high and it was earlier as well.
10	Currently temperature is OK and it was earlier as well.
11	Currently temperature is OK, but earlier it has been too high.
"""
    bist_ot_rx_off_mask.doc = """BIST OTP RX off mask
	0 = Turn off corresponding function in RX
	1 = Allow corresponding bit in trx_rx_off to control on/off of function
Bits
20	Enable RX Q Baseband Output buffer
19	Enable RX Q Baseband Input Buffer, VGA1-3
18	Enable RX I Baseband Output buffer
17	Enable RX I Baseband Input Buffer, VGA1-3
16	Enable RX mixer- and LO-buffer, VGA and LNA
15:0	Mask of RX RF port 15-0 Enables"""
    bist_ot_tx_off_mask.doc = """BIST OTP TX off mask
	0 = Turn off corresponding function in RX
	1 = Allow corresponding bit in trx_tx_off to control on/off of function
Bits
20	Enable TX PA bias loop
19	Enable TX phase shifter VGAs
18	Enable TX Q Baseband
17	Enable TX I Baseband
16	Enable TX mixer- and LO-buffer, VGA and PA
15:0	Mask of  TX RF port 15-0 Enables"""
    spare.doc = """Spare registers
Bits
31:0	Unused"""
    chip_id.doc = """Chip Identification / Chip Identifcation Shadow
(Big-endian, i.e MSB first).
This register doubles as Read-only (RO) Chip Idenfication and
Read/Write (RW) Chip Identification Shadow register.
Chip Identification Shadow is always written when this register
is written.
"""
    chip_id_sw_en.doc = """Configure access of Chip Idenification / Chip Identification Shadow register
chip_id_sw_en = 0:
	Read: Chip Identification, Write: Chip Identification Shadow
chip_id_sw_en = 1:
	Read/Write: Chip Identification Shadow"""
    fast_clk_ctrl.doc = """Fast clock control.
 Controls if the internal digital system clock
is generated by an external clock on GPIO DIG_CLK
or from an internal PLL synchronised to a reference
clock on REF_P/REF_N-pins.
The internal digital clock can also be fed out on GPIO DIG_CLK.
Bits
0	External source select
1	GPIO DIG_CLK output enable for fast clock
4	fast clock frequency select. (0 = 4xRef clock frequency, 1 = 5xRef clock frequency)
5	Ref clock select (1: 45 MHz, 0: 40 MHz)"""
    gpio_tx_rx_sw_ctrl.doc = """GPIO TX_RX_SW control
Bits
0	TX_RX_SW output value
1	TX_RX_SW output enable (1=enable, 0=disable)
4	TX_RX_SW input value (Read-only)"""
    gpio_agc_rst_ctrl.doc = """GPIO AGC_RST control
Bits
0	AGC_RST output value
1	AGC_RST output enable (1=enable, 0=disable)
4	AGC_RST input value (Read-only)"""
    gpio_agc_start_ctrl.doc = """GPIO AGC_START control
Bits
0	AGC_START output value
1	AGC_START output enable (1=enable, 0=disable)
4	AGC_START input value (Read-only)"""
    gpio_agc_gain_in_ctrl.doc = """GPIO AGC_GAIN_x input/output value (x=3, 2, 1 or 0)
Bits
3:0	AGC_GAIN_x output value (x corresponds to bit position)
7:4	AGC_GAIN_x input value (Read-only)"""
    gpio_agc_gain_out_ctrl.doc = """GPIO AGC_GAIN_x output control
Bits
3:0	AGC_GAIN_x output enable (1=enable, 0=disable, x corresponds to bit position)
7:4	AGC_GAIN_x source select (0=AGC state machine, 1=this register)"""
    bist_amux_ctrl.doc = """BIST Analog Mux Control
Controls which internal analog source is connected to the AMUX-pin and to the internal ADC.
Bits
3:0	Analog Mux select
6	DC Sense calibration (1=short DC sense diff input)
7	Analog mux enable
Analog mux select
0	BG PLL
1	BG TX
2	BG RX
3	Temperature
4	BB_RX
5	PLL/VCO
6	VCC PLL
7	TX Power Detector (Peak)
8	ADC reference
9	DC Sense I-channel
10	DC Sense Q-channel
11	DC Sense common mode
12	OTP control
13	TX Power detector (Envelope)
14	VCC PA * 3/4
15	VCC TX * 3/4"""
    bist_ot_ctrl.doc = """BIST Overtemp protection (OTP) control
Controls which OTP source to connect to AMUX-pin and ADC.
Enables/Disables OTP function and OTP Alarm function.
The OTP function controls which parts of the chip should be turned off, if the temperature becomes too high.
Normally it is sufficient that the temperature drops below the treshold, to resume the turned off parts on again.
The OTP Alarm function enables the OTP function to keep these parts off until the OTP Alarm bit has been cleared instead.
Bits
1:0	OTP control
4	OTP enable (0=disable)
5	OTP Alarm enable (0=disable)

OTP control
00	Temp Threshold
01	VDD 1.8 V 
10	VDD 1.2 V
11	VCC RX * 3/4"""
    bist_ot_temp.doc = """BIST OTP Temperature Threshold
Sets threshold level for comparator indicating whether temperature is ok or not.
OTP temperature OK bit shows this indication. OTP Alarm bit shows if any temperature not OK indication has occurred
since last time the OTP Alarm was cleared.
Bits
4:0	OTP threshold value
6	OTP Alarm (Read-only, Cleared when written with 1)
7	OTP temperature OK (Read-only)

Bits 7:6 interpretation
00	Currently temperature is too high, but not earlier.
01	Currently temperature is too high and it was earlier as well.
10	Currently temperature is OK and it was earlier as well.
11	Currently temperature is OK, but earlier it has been too high.
"""
    bist_ot_rx_off_mask.doc = """BIST OTP RX off mask
	0 = Turn off corresponding function in RX
	1 = Allow corresponding bit in trx_rx_off to control on/off of function
Bits
20	Enable RX Q Baseband Output buffer
19	Enable RX Q Baseband Input Buffer, VGA1-3
18	Enable RX I Baseband Output buffer
17	Enable RX I Baseband Input Buffer, VGA1-3
16	Enable RX mixer- and LO-buffer, VGA and LNA
15:0	Mask of RX RF port 15-0 Enables"""
    bist_ot_tx_off_mask.doc = """BIST OTP TX off mask
	0 = Turn off corresponding function in RX
	1 = Allow corresponding bit in trx_tx_off to control on/off of function
Bits
20	Enable TX PA bias loop
19	Enable TX phase shifter VGAs
18	Enable TX Q Baseband
17	Enable TX I Baseband
16	Enable TX mixer- and LO-buffer, VGA and PA
15:0	Mask of  TX RF port 15-0 Enables"""
