#!/usr/bin/env python3

import os

import click

piradio_required_groups = [
    'piradio', 'i2c', 'spi', 'gpio'
]

@click.group(name="piradio-admin")
def piradio_admin():
    """Pi Radio administration tool"""
    pass

@piradio_admin.command("grant-user")
@click.argument("username") 
def grant_user(username):
    """Grant a user the permissions needed to use the radio hardware"""
    for groupname in piradio_required_groups:
        os.system(f"usermod -a -G {groupname} {username}")
    print(f"User {username} has been granted permission to use the radio hardware")

@piradio_admin.command("revoke-user")
@click.argument("username") 
def revoke_user(username):
    """Revoke the permissions needed to use the radio hardware from a user"""
    for groupname in piradio_required_groups:
        os.system(f"deluser {username} {groupname}")
    print(f"User {username} had their permission to use the radio hardware revoked")

if __name__=="__main__":
    piradio_admin()
