# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: siversd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='siversd.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rsiversd.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x16\n\tNumRadios\x12\t\n\x01N\x18\x01 \x01(\r2=\n\x07siversd\x12\x32\n\x0cGetNumRadios\x12\x16.google.protobuf.Empty\x1a\n.NumRadiosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_NUMRADIOS = _descriptor.Descriptor(
  name='NumRadios',
  full_name='NumRadios',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='N', full_name='NumRadios.N', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['NumRadios'] = _NUMRADIOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumRadios = _reflection.GeneratedProtocolMessageType('NumRadios', (_message.Message,), dict(
  DESCRIPTOR = _NUMRADIOS,
  __module__ = 'siversd_pb2'
  # @@protoc_insertion_point(class_scope:NumRadios)
  ))
_sym_db.RegisterMessage(NumRadios)



_SIVERSD = _descriptor.ServiceDescriptor(
  name='siversd',
  full_name='siversd',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=70,
  serialized_end=131,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetNumRadios',
    full_name='siversd.GetNumRadios',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_NUMRADIOS,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIVERSD)

DESCRIPTOR.services_by_name['siversd'] = _SIVERSD

# @@protoc_insertion_point(module_scope)
